from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(ListOfStructure)
admin.site.register(StructureGroup)
admin.site.register(MonopoleDeadend)
admin.site.register(UploadedFile1)
admin.site.register(MonopoleDeadend1)
admin.site.register(MonopoleDeadend4)
admin.site.register(UploadedFile2)
admin.site.register(UploadedFile22)
admin.site.register(UploadedFile4)
admin.site.register(TowerDeadend)
admin.site.register(tUploadedFile1)  
admin.site.register(TowerDeadend3)
admin.site.register(TowerDeadend4)
admin.site.register(TowerDeadend5)
admin.site.register(tUploadedFile3)  
admin.site.register(tUploadedFile4)  
admin.site.register(tUploadedFile5)    
admin.site.register(HDeadend1)  
admin.site.register(hUploadedFile1)  
admin.site.register(LoadCaseGroup)
admin.site.register(LoadCase)
admin.site.register(LoadCondition)
admin.site.register(AttachmentLoad)
admin.site.register(tUploadedFile2)
admin.site.register(HDeadend3)
admin.site.register(hUploadedFile3)
admin.site.register(hUploadedFile2) 
admin.site.register(hUploadedFile4) 