# Generated by Django 5.1.2 on 2025-12-01 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadConditionSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('is_selected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('load_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.loadcondition')),
            ],
            options={
                'ordering': ['group_name', 'load_condition__description'],
                'unique_together': {('group_name', 'load_condition')},
            },
        ),
    ]
