# Generated by Django 5.1.2 on 2025-04-28 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_monopoledeadend'),
    ]

    operations = [
        migrations.AddField(
            model_name='monopoledeadend',
            name='structure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monopole_deadends', to='app1.listofstructure'),
            preserve_default=False,
        ),
    ]
