# Generated by Django 5.1.2 on 2025-12-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_loadconditionselection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadconditionselection',
            options={},
        ),
        migrations.RenameField(
            model_name='loadconditionselection',
            old_name='group_name',
            new_name='custom_group_name',
        ),
        migrations.AlterUniqueTogether(
            name='loadconditionselection',
            unique_together={('custom_group_name', 'load_condition')},
        ),
        migrations.RemoveField(
            model_name='loadconditionselection',
            name='updated_at',
        ),
    ]
