# Generated by Django 5.1.2 on 2025-12-03 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_loadconditionselection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_file', models.FileField(upload_to='3d_models/')),
                ('model_type', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='model_thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='StructureModelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_type', models.CharField(max_length=50)),
                ('configuration', models.CharField(max_length=200)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.threedmodel')),
            ],
            options={
                'unique_together': {('structure_type', 'configuration')},
            },
        ),
    ]
