# Generated by Django 5.1.2 on 2025-12-07 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_threedmodel_structuremodelmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('page1_selections', models.JSONField(default=dict)),
                ('page2_selections', models.JSONField(default=dict)),
                ('page3_selections', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GLBModelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_type', models.CharField(max_length=50)),
                ('popup_path', models.CharField(max_length=255)),
                ('num_3_phase_circuits', models.IntegerField(default=0)),
                ('num_shield_wires', models.IntegerField(default=0)),
                ('num_1_phase_circuits', models.IntegerField(default=0)),
                ('num_communication_cables', models.IntegerField(default=0)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='mapped_models/')),
                ('is_fallback', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=1)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.towermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='StructureModelMapping',
        ),
        migrations.DeleteModel(
            name='ThreeDModel',
        ),
    ]
