# Generated by Django 5.1.2 on 2025-04-28 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_monopoledeadend_num_1_phase_circuits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='app1.listofstructure')),
            ],
        ),
    ]
