# Generated by Django 5.1.2 on 2025-04-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_uploadedfile1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofstructure',
            name='structure',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
