# Generated by Django 5.1.2 on 2025-12-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_sessiontracking_glbmodelmapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glbmodelmapping',
            name='model',
        ),
        migrations.DeleteModel(
            name='SessionTracking',
        ),
        migrations.DeleteModel(
            name='GLBModelMapping',
        ),
    ]
