# Generated by Django 5.1.2 on 2025-12-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_glbmodelmapping_model_delete_sessiontracking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_type', models.CharField(max_length=50)),
                ('config_key', models.CharField(max_length=100)),
                ('circuit_values_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('model_file', models.FileField(upload_to='3d_models/')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('structure_type', 'config_key', 'circuit_values_hash')},
            },
        ),
    ]
