# Generated by Django 5.1.2 on 2025-12-10 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_modelmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_type', models.CharField(max_length=50)),
                ('hframe_option', models.CharField(blank=True, max_length=50)),
                ('configuration', models.CharField(blank=True, max_length=50)),
                ('insulator_type', models.CharField(blank=True, max_length=50)),
                ('deadend_model', models.CharField(blank=True, max_length=50)),
                ('circuit_data_id', models.IntegerField(blank=True, null=True)),
                ('uploaded_file_id', models.IntegerField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.listofstructure')),
                ('structure_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.structuregroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ModelMapping',
        ),
    ]
