# Generated by Django 5.1.2 on 2025-04-29 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_monopoledeadend_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monopoledeadend',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monopole_deadends', to='app1.listofstructure', unique=True),
        ),
    ]
