# Generated by Django 5.1.2 on 2025-12-10 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_structureselection_delete_modelmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_type', models.CharField(max_length=20)),
                ('hframe_configuration', models.CharField(blank=True, max_length=50)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hdeadend1_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.hdeadend1')),
                ('selected_3d_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.towermodel')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.listofstructure')),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.huploadedfile1')),
            ],
        ),
        migrations.DeleteModel(
            name='StructureSelection',
        ),
    ]
