# Generated by Django 5.1.2 on 2025-12-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_projectconfiguration_delete_structureselection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectConfiguration',
        ),
    ]
