# Generated by Django 5.1.2 on 2025-05-02 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_monopoledeadend_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonopoleDeadend1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_3_phase_circuits', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('num_shield_wires', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('num_1_phase_circuits', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('num_communication_cables', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='monopoledeadend',
            constraint=models.UniqueConstraint(fields=('structure',), name='unique_monopole_per_structure'),
        ),
        migrations.AddConstraint(
            model_name='uploadedfile1',
            constraint=models.UniqueConstraint(fields=('structure',), name='unique_file_per_structure'),
        ),
        migrations.AddField(
            model_name='monopoledeadend1',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monopole_deadends1', to='app1.listofstructure', unique=True),
        ),
        migrations.AddField(
            model_name='uploadedfile2',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files1', to='app1.listofstructure'),
        ),
        migrations.AddConstraint(
            model_name='monopoledeadend1',
            constraint=models.UniqueConstraint(fields=('structure',), name='unique_monopole_per_structure1'),
        ),
        migrations.AddConstraint(
            model_name='uploadedfile2',
            constraint=models.UniqueConstraint(fields=('structure',), name='unique_file_per_structure1'),
        ),
    ]
