# Generated by Django 5.1.2 on 2025-12-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_delete_projectconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('structure_type', models.CharField(choices=[('tower', 'Tower'), ('hframe', 'H-Frame'), ('monopole', 'Monopole')], max_length=50)),
                ('popup_type', models.CharField(blank=True, choices=[('deadend', 'Deadend'), ('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('tangent', 'Tangent'), ('post-insulator', 'Post Insulator'), ('v-string', 'V-String')], max_length=50, null=True)),
                ('model_file', models.FileField(upload_to='3d_models/glb/')),
                ('num_3_phase_circuits', models.PositiveIntegerField(default=0)),
                ('num_shield_wires', models.PositiveIntegerField(default=0)),
                ('num_1_phase_circuits', models.PositiveIntegerField(default=0)),
                ('num_communication_cables', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
