# Generated by Django 5.1.2 on 2025-12-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_structuremodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StructureModel',
        ),
    ]
