# Generated by Django 5.1.2 on 2025-05-12 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_monopoledeadend4'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files4', to='app1.listofstructure')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('structure',), name='unique_file_per_structure4')],
            },
        ),
    ]
