# Generated by Django 5.1.2 on 2025-12-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_delete_structuremodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='towermodel',
            name='attachment_points',
            field=models.CharField(blank=True, choices=[('deadend', 'Deadend'), ('tangent', 'Tangent')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='towermodel',
            name='circuit_1_phase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='towermodel',
            name='circuit_3_phase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='towermodel',
            name='circuit_communication',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='towermodel',
            name='circuit_shield_wires',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='towermodel',
            name='configuration',
            field=models.CharField(blank=True, choices=[('vertical', 'Vertical'), ('delta', 'Delta'), ('horizontal', 'Horizontal'), ('post_insulator', 'Post Insulator'), ('v_string', 'V-String'), ('i_string', 'I-String'), ('brace_post', 'Brace Post Insulator')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='towermodel',
            name='structure_type',
            field=models.CharField(blank=True, choices=[('towers', 'Towers'), ('hframes', 'H-Frames'), ('monopoles', 'Monopoles')], max_length=50, null=True),
        ),
    ]
