# Generated by Django 5.1.2 on 2025-12-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_towermodel_attachment_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='towermodel',
            old_name='circuit_1_phase',
            new_name='num_1_phase_circuits',
        ),
        migrations.RenameField(
            model_name='towermodel',
            old_name='circuit_3_phase',
            new_name='num_3_phase_circuits',
        ),
        migrations.RenameField(
            model_name='towermodel',
            old_name='circuit_communication',
            new_name='num_communication_cables',
        ),
        migrations.RenameField(
            model_name='towermodel',
            old_name='circuit_shield_wires',
            new_name='num_shield_wires',
        ),
        migrations.AlterField(
            model_name='towermodel',
            name='configuration',
            field=models.CharField(blank=True, choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('delta', 'Delta')], max_length=50, null=True),
        ),
    ]
