# Generated by Django 5.1.2 on 2025-12-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_circuit_1_phase_towermodel_num_1_phase_circuits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towermodel',
            name='num_1_phase_circuits',
        ),
        migrations.RemoveField(
            model_name='towermodel',
            name='num_3_phase_circuits',
        ),
        migrations.RemoveField(
            model_name='towermodel',
            name='num_communication_cables',
        ),
        migrations.RemoveField(
            model_name='towermodel',
            name='num_shield_wires',
        ),
        migrations.AddField(
            model_name='towermodel',
            name='circuit_type',
            field=models.CharField(blank=True, choices=[('sc', 'Single Circuit'), ('dc', 'Double Circuit'), ('tc', 'Triple Circuit')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='towermodel',
            name='configuration',
            field=models.CharField(blank=True, choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('delta', 'Delta'), ('hetic', 'Hetic')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='towermodel',
            name='structure_type',
            field=models.CharField(choices=[('towers', 'Towers'), ('hframes', 'H-Frames'), ('monopoles', 'Monopoles')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
