# Generated by Django 5.1.2 on 2025-12-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_towermodel_num_1_phase_circuits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='towermodel',
            name='circuit_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='towermodel',
            name='num_1_phase_circuits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='towermodel',
            name='num_3_phase_circuits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='towermodel',
            name='num_communication_cables',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='towermodel',
            name='num_shield_wires',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='towermodel',
            name='attachment_points',
            field=models.CharField(blank=True, choices=[('deadend', 'Deadend'), ('tangent', 'Tangent')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='towermodel',
            name='circuit_type',
            field=models.CharField(blank=True, choices=[('sc', 'Single Circuit'), ('dc', 'Double Circuit'), ('tc', 'Triple Circuit')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='towermodel',
            name='configuration',
            field=models.CharField(blank=True, choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('delta', 'Delta'), ('hetic', 'Hetic')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='towermodel',
            name='structure_type',
            field=models.CharField(blank=True, choices=[('towers', 'Towers'), ('hframes', 'H-Frames'), ('monopoles', 'Monopoles')], max_length=20, null=True),
        ),
    ]
