# Generated by Django 5.1.2 on 2025-12-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_towermodel_circuit_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towermodel',
            name='circuit_config',
        ),
        migrations.RemoveField(
            model_name='towermodel',
            name='num_1_phase_circuits',
        ),
        migrations.RemoveField(
            model_name='towermodel',
            name='num_3_phase_circuits',
        ),
        migrations.RemoveField(
            model_name='towermodel',
            name='num_communication_cables',
        ),
        migrations.RemoveField(
            model_name='towermodel',
            name='num_shield_wires',
        ),
    ]
