# Generated by Django 5.1.2 on 2025-08-28 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_hdeadend2_huploadedfile2'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadCaseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hload_case_groups', to='app1.listofstructure')),
            ],
        ),
        migrations.CreateModel(
            name='LoadCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hload_cases', to='app1.listofstructure')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='load_cases', to='app1.loadcasegroup')),
            ],
        ),
    ]
