# Generated by Django 5.1.2 on 2025-09-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_loadcasegroup_loadcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadcasegroup',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
