# Generated by Django 5.1.2 on 2025-09-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_loadcasegroup_is_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('temperature', models.FloatField(verbose_name='°F')),
                ('ice_radial', models.FloatField(verbose_name='Radial (in)')),
                ('wind_pressure', models.FloatField(verbose_name='Pressure (psf)')),
                ('angle_factor', models.FloatField()),
                ('transverse_factor', models.FloatField()),
                ('vertical_factor', models.FloatField()),
                ('longitudinal_factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_case', models.CharField(choices=[('LC1', 'LC1, NESC LIGHT (250B)'), ('LC2', 'LC2, NESC EXTREME WIND (250C)'), ('LC3', 'LC3, NESC COMBINED ICE AND WIND (250D)'), ('LC4', 'LC4, NORMAL EVERYDAY'), ('LC5', 'LC5, 2% POLE DEFLECTION'), ('LC6', 'LC6, FULL BREAK (250B)'), ('LC7', 'LC7, Full Break (250D)')], max_length=3)),
                ('attachment', models.CharField(choices=[('S1', 'S1'), ('P1,A', 'P1,A'), ('P1,B', 'P1,B'), ('P1,C', 'P1,C'), ('F1', 'F1'), ('D1,A & D2,A', 'D1,A & D2,A'), ('D1,B & D2,B', 'D1,B & D2,B'), ('D1,C & D2,C', 'D1,C & D2,C'), ('N1 & N2', 'N1 & N2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4')], max_length=20)),
                ('vertical_load', models.FloatField(verbose_name='V')),
                ('transverse_load', models.FloatField(verbose_name='T')),
                ('longitudinal_load', models.FloatField(verbose_name='L')),
            ],
            options={
                'unique_together': {('load_case', 'attachment')},
            },
        ),
    ]
