# Generated by Django 5.1.2 on 2025-09-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_hdeadend2_num_1_phase_circuits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towerdeadend',
            name='num_1_phase_circuits',
            field=models.PositiveIntegerField(choices=[(0, '0'), (None, 'None'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
        migrations.AlterField(
            model_name='towerdeadend',
            name='num_3_phase_circuits',
            field=models.PositiveIntegerField(choices=[(0, '0'), (None, 'None'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
        migrations.AlterField(
            model_name='towerdeadend',
            name='num_communication_cables',
            field=models.PositiveIntegerField(choices=[(0, '0'), (None, 'None'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
        migrations.AlterField(
            model_name='towerdeadend',
            name='num_shield_wires',
            field=models.PositiveIntegerField(choices=[(0, '0'), (None, 'None'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
