# Generated by Django 5.1.2 on 2025-09-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_towerdeadend_num_1_phase_circuits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BufferConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Buffer Config', max_length=100)),
                ('vertical_buffer', models.FloatField(default=0)),
                ('vertical_rounding', models.IntegerField(default=100)),
                ('transverse_buffer', models.FloatField(default=0)),
                ('transverse_rounding', models.IntegerField(default=100)),
                ('longitudinal_buffer', models.FloatField(default=0)),
                ('longitudinal_rounding', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
