# Generated by Django 5.1.2 on 2025-09-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_alter_hdeadend1_num_1_phase_circuits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdeadend2',
            name='num_1_phase_circuits',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='hdeadend2',
            name='num_3_phase_circuits',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='hdeadend2',
            name='num_communication_cables',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='hdeadend2',
            name='num_shield_wires',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
    ]
