# Generated by Django 5.1.2 on 2025-09-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_remove_monopoledeadend_unique_monopole_per_structure_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monopoledeadend',
            name='munique_monopole_per_structure1',
        ),
        migrations.AlterField(
            model_name='monopoledeadend',
            name='num_1_phase_circuits',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monopoledeadend',
            name='num_3_phase_circuits',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monopoledeadend',
            name='num_communication_cables',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monopoledeadend',
            name='num_shield_wires',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='monopoledeadend',
            constraint=models.UniqueConstraint(fields=('structure',), name='unique_monopole_per_structure'),
        ),
    ]
