# Generated by Django 5.1.2 on 2025-09-19 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_remove_monopoledeadend_munique_monopole_per_structure1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile1',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muploaded_files1', to='app1.listofstructure'),
        ),
        migrations.CreateModel(
            name='UploadedFile22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files22', to='app1.listofstructure')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile3',
        ),
        migrations.AddConstraint(
            model_name='uploadedfile22',
            constraint=models.UniqueConstraint(fields=('structure',), name='unique_file_per_structure22'),
        ),
    ]
