# Generated by Django 5.1.2 on 2025-09-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_mdeadend12_mdeadend13_muploadedfile12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='huploadedfile1',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='huploadedfile1',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
