# Generated by Django 5.1.2 on 2025-09-30 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_huploadedfile1_updated_at_huploadedfile1_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huploadedfile1',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='huploadedfile1',
            name='version',
        ),
    ]
