# Generated by Django 5.1.2 on 2025-10-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_remove_huploadedfile1_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('structures', models.ManyToManyField(related_name='groups', to='app1.listofstructure')),
            ],
        ),
    ]
