# Generated by Django 5.1.2 on 2025-10-16 12:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0051_delete_threedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('glb_file', models.FileField(upload_to='3d_models/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_properties', models.JSONField(blank=True, default=dict)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_d_models', to='app1.listofstructure')),
            ],
        ),
    ]
