# Generated by Django 5.1.2 on 2025-10-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_threedmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThreeDModel',
        ),
    ]
