# Generated by Django 5.1.2 on 2025-11-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_towermodel3d'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TowerModel3D',
        ),
    ]
