# Generated by Django 5.1.2 on 2025-11-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0055_delete_towermodel3d'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowerModel3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('model_file', models.FileField(upload_to='3d_models/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='3d_model_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
